<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Data\Data.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Ioc\Ioc.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\LICENSE" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\additional-methods.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\LICENSE.md" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.slim.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.slim.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.slim.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\dana-fanum-regular.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\dana-fanum-regular.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\feather-font\css\iconfont.css" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\feather-font\fonts\feather.eot" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\feather-font\fonts\feather.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\feather-font\fonts\feather.ttf" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\feather-font\fonts\feather.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\IRANSansWeb_Light.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\IRANSansWeb_Light.woff2" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\themify\css\themify.css" />
      <_ContentIncludedByDefault Remove="wwwroot\fonts\themify\themify.woff" />
      <_ContentIncludedByDefault Remove="wwwroot\js\ace.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\apexcharts-dark-rtl.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\apexcharts-dark.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\apexcharts-light-rtl-horizontal.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\apexcharts-light-rtl.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\apexcharts-light.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\bootstrap-colorpicker.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\bootstrap-maxlength.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\calendar-jallali\fa.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\calendar-jallali\fullcalendar.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\calendar-jallali\jquery-ui.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\calendar-jallali\jquery.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\calendar-jallali\moment-jalaali.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\calendar-jallali\moment.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\carousel-rtl.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\carousel.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\chartjs-dark-rtl.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\chartjs-dark.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\chartjs-light-rtl.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\chartjs-light.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\chat.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\cropper.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\dashboard-dark.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\dashboard-light-horizontal.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\dashboard-light.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\data-table.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\datepicker.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\demo.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\dropify.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\dropzone.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\easymde.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\email.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\flatpickr.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\form-validation.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\fullcalendar.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\inputmask.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\jquery.flot-dark.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\jquery.flot-light.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\morrisjs-dark.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\morrisjs-light.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\peity.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\persian-date-0.1.8.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\persian-datepicker-0.4.5.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\pickr.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\select2.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\simplemde.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\sortablejs-dark.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\sortablejs-light.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\sparkline.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\sweet-alert.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\tags-input.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\template.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\timepicker.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\tinymce.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\to-do.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\typeahead.js" />
      <_ContentIncludedByDefault Remove="wwwroot\js\wizard.js" />
      <_ContentIncludedByDefault Remove="Views\Transaction\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\Transaction\Index.cshtml" />
    </ItemGroup>

</Project>
